### PR TITLE
[Gamemode]: Supporting MCDR 2.x & updating tp method

### PR DESCRIPTION
**Pull request by EasonSYC**
I changed the structure of the gamemode folder and added the two APIs to this folder. After testing in my server (MCDReforged 2.3.2), it is possible to use all the functions.

### CODE REVIEW

**Comment by EasonSYC** [comment]
While testing, i found a bug: the dimension and the coordinates are not shown correctly. Therefore, i also made a commit of !!tp code, which adds support for !!tp [dimension] [position] (at least 1 param), supporting:
 - !!tp <x> <y> <z>
 - !!tp <dim> <x> <y> <z>
 - !!tp <dim> with calculations between overworld and nether.

I look forward to merging my Pull Request into your master branch and being published into a .mcdr file.

**Comment by zhang-anzhi** [comment]
There is issue that I was taken soooooo long time do not develop MCDR plugin, so I could not test it, if anyone could help to review the change weill great.
I would like to ask of move these two APIs in to same path: is there any other better way to do same thing? I know there is a MCDR API to read-write JSON file and config file, I remembered that I used it in other plugin.
Also there is a logic change of the origin plugin, could you describe what changes you make? Thanks!

**Comment by EasonSYC** [comment]
The !!tp change is as following:

I registered 4 params into the tp, a as text, b, c, d as float.

This could support more kinds of 'tp', for example:
- !!tp dimension, where only the param a is used;
- !!tp x y z, where a, b, c is used;
- !!tp dimension x y z, where all 4 are used.

To avoid having meaningless coords in !!tp x y z, i added a function called `coordValid` to make sure the text param `a` is working normally.

To convert the coords between overworld and the nether, i added two functions: `nether_to_overworld` and `overworld_to_nether`.

This logic is used in my server for approximately 6 months (but i have never commited it) and i believe is bug-free.

**Comment by EasonSYC** [comment]
Currently i have no idea on reducing the Python files in the folder :(

**Comment by EasonSYC** [comment]
IMG_5660

IMG_5661

These are two photos of how the plugin is working on my own server. (From the grey part you can see how the conversion between different dimensions work.

**Comment by EasonSYC** [comment]
Working log is as following:

> <EasonSYC> !!spec
> EasonSYC has the following entity data: "minecraft:overworld"
> EasonSYC has the following entity data: [63.880419795270356d, 11.0d, 112.82662495942499d]
> Set EasonSYC's game mode to Spectator Mode



> <EasonSYC> !!tp 0 1 2 3
> EasonSYC has the following entity data: "minecraft:overworld"
> EasonSYC has the following entity data: [63.880419795270356d, 11.0d, 112.82662495942499d]
> Teleported EasonSYC to 1.0, 2.0, 3.0



> <EasonSYC> !!tp 0 8 8 8
> [EasonSYC has the following entity data: "minecraft:overworld"
> EasonSYC has the following entity data: [1.0d, 2.0d, 3.0d]
> Teleported EasonSYC to 8.0, 8.0, 8.0



> <EasonSYC> !!tp -1
> EasonSYC has the following entity data: "minecraft:overworld"
> EasonSYC has the following entity data: "minecraft:overworld"
> EasonSYC has the following entity data: [8.0d, 8.0d, 8.0d]
> EasonSYC has the following entity data: "minecraft:overworld"
> EasonSYC has the following entity data: [8.0d, 8.0d, 8.0d]
> Teleported EasonSYC to 1.5, 8.0, 1.5



> <EasonSYC> !!back
> EasonSYC has the following entity data: "minecraft:the_nether"
> EasonSYC has the following entity data: [1.5d, 8.0d, 1.5d]
> Teleported EasonSYC to 8.5, 8.0, 8.5



> <EasonSYC> !!tp 2 3 4
> EasonSYC has the following entity data: "minecraft:overworld"
> EasonSYC has the following entity data: "minecraft:overworld"
> EasonSYC has the following entity data: [8.5d, 8.0d, 8.5d]
> Teleported EasonSYC to 2.0, 3.0, 4.0



> <EasonSYC> !!tp the_end
> EasonSYC has the following entity data: "minecraft:overworld"
> EasonSYC has the following entity data: "minecraft:overworld"
> EasonSYC has the following entity data: [2.0d, 3.0d, 4.0d]
> Teleported EasonSYC to 0.5, 80.0, 0.5
> Scanning for legacy world dragon fight...
> Found that the dragon has been killed in this world already.



> <EasonSYC> !!spec
> Teleported EasonSYC to 63.880419795270356, 11.0, 112.82662495942499
> Set EasonSYC's game mode to Survival Mode

**Comment by zhang-anzhi** [comment]
- [ ] it looks like `a b c` means `x y z` in !!tp, please change abc to xyz to help to understand

**Comment by zhang-anzhi** [comment]
Thanks again to your update of the plugin, it looks work well during 6 months test

**Comment by EasonSYC** [comment]
I added some description of what each param is used for in different situations of !!tp command. a b c is not always x y z, and the description should be clear enough to state which one is which.

I used the same way to remove config as ColoredChat but currently is unable to remove json (as the keys in the json is playername and it is impossible to do as ColoredChat).

**Comment by EasonSYC** [comment]
While using command `!!tp <dimension>`, param 1 stands for dimension.
While using command `!!tp <x> <y> <z>`, param 1, 2, 3 stands for x, y, z.
While using command `!!tp <dimension> <x> <y> <z>`, param 1 stands for dimension while param 2, 3, 4 stands for x, y, z.

**Comment by zhang-anzhi** [comment]
Actually, it is possiable to use MCDR API to replace JsonDataAPI.
But that is not important in a long-no-update plugin, I will merge your change. If there would be any one like to continue update it, I am welcome and happy to accept.

**Pull request merged**
